index:
  path: /
  controller: App\Controller\IndexController::index

stops:
  path: /stops
  controller: App\Controller\IndexController::stops

departures:
  path: /departures
  controller: App\Controller\IndexController::departures

boards:
  path: /board/{name}
  controller: App\Controller\BoardsController::index
  defaults:
    name: 'home'
  requirements:
    name: '\w+'

api_boards:
  path: /api/boards
  controller: App\Controller\ApiController::boards
  methods: [GET]

api_board:
  path: /api/board/{name}
  controller: App\Controller\ApiController::board
  defaults:
    name: 'home'
  requirements:
    name: '\w+'
  methods: [GET]

api_stops:
  path: /api/stops
  controller: App\Controller\ApiController::stops
  methods: [GET]

api_departures:
  path: /api/departures
  controller: App\Controller\ApiController::departures
  methods: [GET]
