index:
  path: /
  controller: App\Controller\IndexController::index

stops:
  path: /stops
  controller: App\Controller\IndexController::rawStops

departures:
  path: /departures
  controller: App\Controller\IndexController::rawDepartures